### PR TITLE
Update to EF Core 7 RC 2

### LINKED ISSUE #10: Support for EF Core 7
What are the plans for EF Core 7 support?

### PR DESCRIPTION
**Pull request by ErikEJ**
fixes #10

### CODE REVIEW

**Comment by khellang** [comment]
Thank you @ErikEJ! 🙏🏻

**Comment by ErikEJ** [comment]
Awesome!

**Comment by khellang** [comment]
I forgot to notify you earlier, but 7.0.0-rc.2 is on NuGet now ☺️

**Comment by ErikEJ** [comment]
Added to latest daily build of EF Core Power Tools

**Pull request merged**
