### PR TITLE
show example of ef recording

### PR DESCRIPTION
**Pull request by SimonCropp**
hey @khellang. i have been experimenting with recording ef statements and then using them in the snapshot. i would appreciate your thoughts on this approach.

Not that this would make your `TestLogger` redundant.

### CODE REVIEW

**Comment by khellang** [comment]
Nice! That's pretty cool. I'll definitely use this. Did you see I used Verify on the migrations tests? https://github.com/khellang/EFCore.Sqlite.NodaTime/blob/master/EFCore.Sqlite.NodaTime.Tests/Migrations/MigrationTests.cs

**Comment by SimonCropp** [comment]
i did see the migration usage. but is doesnt seem like u accepted the changes?

**Comment by khellang** [comment]
[I did](https://github.com/khellang/EFCore.Sqlite.NodaTime/blob/master/EFCore.Sqlite.NodaTime.Tests/Migrations/MigrationTests.Migration_Generates_Correct_SnapshotCode.verified.cs), but there are some issues with SQLite detecting no pending changes on subsequent runs, which is why the test is failing.

**Comment by SimonCropp** [comment]
i updated the rest to snapshot testing

**Comment by khellang** [comment]
This is awesome! Thanks so much 😎

**Pull request merged**
